### ISSUE TITLE
fail to bundle Colors.py with extension

### ISSUE THREAD

**Issue by pieper** [acil-bwh/SlicerCIP#10]
Installing the latest CIP fails with messages like the one below (on linux, but probably the same everywhere).

Key error is:
**ImportError: No module named Colors**

I manually copied the Colors.py file into the logic folder and this resolved the problem for my installation.

The fix would be to explicitly include the Colors.py file in the installation:

https://github.com/acil-bwh/SlicerCIP/blob/develop/Scripted/CIP_Common/CMakeLists.txt#L5

Looks like the problem arose with this commit: https://github.com/acil-bwh/SlicerCIP/commit/62afe4c324165b316a1f37f2cbe0d87069ae4de9

@acil-bwh @rjosest 

```
The following path was manually added to the PythonPath in CIP_TracheaStentPlanning: /home/researcher/.config/NA-MIC/Extensions-25011/Chest_Imaging_Platform/lib/Slicer-4.5/qt-scripted-modules/CIP
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/researcher/.config/NA-MIC/Extensions-25011/Chest_Imaging_Platform/lib/Slicer-4.5/qt-scripted-modules/CIP_TracheaStentPlanning.py", line 26, in <module>
    from CIP.logic.SlicerUtil import SlicerUtil
  File "/home/researcher/.config/NA-MIC/Extensions-25011/Chest_Imaging_Platform/lib/Slicer-4.5/qt-scripted-modules/CIP/logic/__init__.py", line 6, in <module>
    from Colors import *
ImportError: No module named Colors
loadSourceAsModule - Failed to load file "/home/researcher/.config/NA-MIC/Extensions-25011/Chest_Imaging_Platform/lib/Slicer-4.5/qt-scripted-modules/CIP_TracheaStentPlanning.py"  as module "CIP_TracheaStentPlanning" ! 
Fail to instantiate module "CIP_TracheaStentPlanning" 
```

**Comment by jonieva** [comment]
Tx Steve.

Fixed

Jorge Onieva
